language: csharp

before_script: 
  - chmod +x build.sh
  - chmod +x package.sh
script:
  - ./build.sh
  - ./package.sh
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == false ] && [ "$TRAVIS_BRANCH" == "master" ]; then 
    nuget push stratos.*.nupkg -ApiKey $APIKey -Source https://push.chocolatey.org/ ;
    fi